#pragma once

enum class ShaderType {
	Graphics,
	Compute,
	Unknown
};


struct EntryPointReflectionData {
	std::string outputFile;
	uint32_t numSamplers = 0;
	uint32_t numStorageBuffers = 0;
	uint32_t numStorageTextures = 0;
	uint32_t numUniformBuffers = 0;
	uint32_t numSampledTextures = 0;

};

struct ComputeShaderReflectionData {

	std::string outputFile;

	uint32_t numSamplers = 0;
	uint32_t numUniformBuffers = 0;

	uint32_t numReadOnlyStorageBuffers = 0;
	uint32_t numReadOnlyStorageTextures = 0;
	uint32_t numReadwriteStorageTextures = 0;
	uint32_t numReadwriteStorageBuffers = 0;

	uint32_t threadCountX = 0;
	uint32_t threadCountY = 0;
	uint32_t threadCountZ = 0;
};

struct ShaderReflectionData {
	EntryPointReflectionData reflectionVS;
	EntryPointReflectionData reflectionFS;
	ComputeShaderReflectionData reflectionCS;
	std::vector<SDL_GPUVertexAttribute> vertexAttributes;
	uint32_t vertexStride = 0;
	ShaderType type;

	SDL_GPUFillMode fillMode = SDL_GPU_FILLMODE_FILL;
	SDL_GPUCullMode cullMode = SDL_GPU_CULLMODE_BACK;
	SDL_GPUFrontFace frontFace = SDL_GPU_FRONTFACE_COUNTER_CLOCKWISE;
	SDL_GPUPrimitiveType primitiveType = SDL_GPU_PRIMITIVETYPE_TRIANGLELIST;
	SDL_GPUCompareOp depthCompareOp = SDL_GPU_COMPAREOP_LESS;
	SDL_GPUColorTargetBlendState blendState = {};
	SDL_GPUTextureFormat depthFormat = SDL_GPU_TEXTUREFORMAT_D32_FLOAT_S8_UINT;
	std::vector<SDL_GPUTextureFormat> colorTargets;
	bool depthTestEnabled = true;
	bool depthWriteEnabled = true;
	bool enableStencilTest = false;
	bool msaaCapable = false;
};

/// <summary>
/// Maps shader reflection data file generated by ShaderCompiler.ixx to ShaderReflectionData
/// </summary>
class ShaderReflectionMapper {


public:

	static bool mapShaderReflection(const fs::path& metaDataFilePath, ShaderReflectionData & reflectionData) {

		std::string filename = metaDataFilePath.stem().string();
		std::filesystem::path folderPath = metaDataFilePath.parent_path();

		std::ifstream file(metaDataFilePath);
		if (!file.is_open()) {
			LogError(LOG_RENDER, "Failed to open file %s", metaDataFilePath.string().c_str());
			return false;
		}

		rapidjson::IStreamWrapper isw(file);
		rapidjson::Document doc;
		doc.ParseStream(isw);

		if (doc.HasParseError()) {
			LogError(LOG_RENDER, "JSON parse error: %s at offset %s in file %s",
				doc.GetParseError(), doc.GetErrorOffset(), metaDataFilePath.string().c_str());
			return false;
		}

		if (doc.IsObject()) {
			LogTrace(LOG_RENDER, "Successfully loaded JSON object from file %s", metaDataFilePath.string().c_str());
		}


		reflectionData.type = determineShaderType(filename, doc);

		switch (reflectionData.type) {
		case ShaderType::Graphics:

		{
			LogTrace(LOG_RENDER, "Detected graphics shader: %s", filename.c_str());

			mapGraphicsShaderReflection(doc, reflectionData, filename);

			//Adding outputFile to shader reflection manually
			//because it does not exist in the slang generated Shader reflection file.

			std::string compiledVSFileName = folderPath.generic_string() + "/" + filename + ".vert" + ".spv";
			if (!fs::exists(compiledVSFileName) && !fs::is_regular_file(compiledVSFileName)) {
				LogError(LOG_RENDER, " Compiled Vertex Shader file %s does not exist", compiledVSFileName.c_str());
			};

			reflectionData.reflectionVS.outputFile = compiledVSFileName;

			std::string compiledFSFileName = folderPath.generic_string() + "/" + filename + ".frag" + ".spv";
			if (!fs::exists(compiledFSFileName) && !fs::is_regular_file(compiledFSFileName)) {
				LogError(LOG_RENDER, " Compiled Fragment Shader file %s does not exist", compiledFSFileName.c_str());
			};

			reflectionData.reflectionFS.outputFile = compiledFSFileName;

			break;
		}
			

		case ShaderType::Compute:

		{
			LogTrace(LOG_RENDER, "Detected compute shader: %s", filename.c_str());

			//Adding outputFile to shader reflection manually
			//because it does not exist in the slang generated Shader reflection file.
			std::string compiledCSFileName = folderPath.generic_string() + "/" + filename + ".comp" + ".spv";
			if (!fs::exists(compiledCSFileName) && !fs::is_regular_file(compiledCSFileName)) {
				LogError(LOG_RENDER, " Compiled Compute Shader file %s does not exist", compiledCSFileName.c_str());
			};
			reflectionData.reflectionCS.outputFile = compiledCSFileName;

			mapComputeShaderReflection(doc, reflectionData, filename);

			break;
		}
			
		case ShaderType::Unknown:
			LogError(LOG_RENDER, "Could not determine shader type for: %s", filename.c_str());
			return false;
		}

		return true;
	}


	static ShaderType determineShaderType(const std::string filename, const rapidjson::Document& doc) {
		if (!doc.HasMember("entryPoints") || !doc["entryPoints"].IsArray()) {
			LogError(LOG_RENDER, "No entryPoints array found in %s reflection JSON ", filename.c_str());
			return ShaderType::Unknown;
		}

		const auto& entryPoints = doc["entryPoints"].GetArray();

		bool hasVertex = false;
		bool hasFragment = false;
		bool hasCompute = false;

		for (const auto& ep : entryPoints) {
			if (!ep.HasMember("stage") || !ep["stage"].IsString())
				continue;

			std::string_view stage = ep["stage"].GetString();

			if (stage == "vertex")   hasVertex = true;
			if (stage == "fragment") hasFragment = true;
			if (stage == "compute")  hasCompute = true;
		}

		if (hasCompute)
			return ShaderType::Compute;

		if (hasVertex && hasFragment)
			return ShaderType::Graphics;

		return ShaderType::Unknown;
	}

	static void mapGraphicsShaderReflection(const rapidjson::Document& doc, ShaderReflectionData& reflectionData,
		const std::string metadataFileName)
	{
		// Iterate entry points and dispatch to VS/FS population
		if (!doc.HasMember("entryPoints") || !doc["entryPoints"].IsArray())
			return;

		for (const auto& ep : doc["entryPoints"].GetArray())
		{
			if (!ep.HasMember("stage") || !ep["stage"].IsString())
				continue;

			std::string_view stage = ep["stage"].GetString();

			if (stage == "vertex")
			{
			
				mapVertexAttributes(ep, reflectionData); 
			}
		}

		// Parse parameters for resource counts (uniform buffers, samplers, etc.)
		if (doc.HasMember("parameters") && doc["parameters"].IsArray())
			mapGraphicsParameters(doc["parameters"], reflectionData, metadataFileName);

	}

	static void mapComputeShaderReflection(const rapidjson::Document& doc, ShaderReflectionData& reflectionData,
		const std::string metadataFileName) {

		// Parse parameters for resource counts (uniform buffers, samplers, etc.)
		if (doc.HasMember("parameters") && doc["parameters"].IsArray()) {

			mapComputeParameters(doc["parameters"], reflectionData, metadataFileName);
			mapComputeThreadCount(doc["entryPoints"], reflectionData);
		}
			

	}

	//SDL_GPU docs on Shader resource bindings explans why space1 = VS ,  space3 = FS etc...
	// https://wiki.libsdl.org/SDL3/SDL_CreateGPUShader
	static void mapGraphicsParameters(const rapidjson::Value& parameters, ShaderReflectionData& reflectionData,
		const std::string metadataFileName)
	{
		bool foundUserAttribs = false;

		for (const auto& param : parameters.GetArray())
		{
			if (param.HasMember("userAttribs"))
				foundUserAttribs = true;
			mapUserAttribs(param, reflectionData, metadataFileName); // checks for userAttribs internally

			if (!param.HasMember("type") || !param["type"].IsObject())    continue;
			if (!param.HasMember("binding") || !param["binding"].IsObject()) continue;

			const auto& type = param["type"];
			const auto& binding = param["binding"];

			if (!type.HasMember("kind") || !type["kind"].IsString()) continue;

			std::string_view kind = type["kind"].GetString();

			// Space is optional — missing space means space0 (VS resource set)
			int space = 0;
			if (binding.HasMember("space") && binding["space"].IsInt())
				space = binding["space"].GetInt();

			// --- Uniform buffers ---
			if (kind == "constantBuffer")
			{
				if (space == 1)       reflectionData.reflectionVS.numUniformBuffers++;
				else if (space == 3)  reflectionData.reflectionFS.numUniformBuffers++;
				continue;
			}

			// --- Samplers ---
			if (kind == "samplerState")
			{
				if (space == 0)       reflectionData.reflectionVS.numSamplers++;
				else if (space == 2)  reflectionData.reflectionFS.numSamplers++;
				continue;
			}

			// --- Resources: texture2D, structuredBuffer, etc. ---
			if (kind == "resource")
			{
				if (!type.HasMember("baseShape") || !type["baseShape"].IsString()) continue;
				std::string_view baseShape = type["baseShape"].GetString();

				if (baseShape == "texture2D")
				{
					if (space == 0)       reflectionData.reflectionVS.numSampledTextures++;
					else if (space == 2)  reflectionData.reflectionFS.numSampledTextures++;
				}
				else if (baseShape == "structuredBuffer")
				{
					// Check access modifier for read-only vs read-write
					// Slang emits "access": "read" for SRV, "readWrite" for UAV
					bool isReadWrite = false;
					if (type.HasMember("access") && type["access"].IsString())
						isReadWrite = std::string_view(type["access"].GetString()) == "readWrite";

					if (space == 0)
						reflectionData.reflectionVS.numStorageBuffers++;
					else if (space == 2)
						reflectionData.reflectionFS.numStorageBuffers++;
				}
				else if (baseShape == "texture2DMS" ||
					baseShape == "textureCube" ||
					baseShape == "texture2DArray")
				{
					// Treat all sampled texture variants the same way for now
					if (space == 0)       reflectionData.reflectionVS.numSampledTextures++;
					else if (space == 2)  reflectionData.reflectionFS.numSampledTextures++;
				}

				continue;
			}

			if (!foundUserAttribs)
				LogWarn(LOG_RENDER, "Shader metadata file %s has no userAttribs - pipeline state will use defaults",
					metadataFileName.c_str());
		}
	}

	static void mapComputeParameters(const rapidjson::Value& parameters, ShaderReflectionData& reflectionData,
		const std::string& metadataFileName)
	{
		for (const auto& param : parameters.GetArray())
		{
			mapUserAttribs(param, reflectionData, metadataFileName);
			if (!param.HasMember("type") || !param["type"].IsObject())      continue;
			if (!param.HasMember("binding") || !param["binding"].IsObject()) continue;

			const auto& type = param["type"];
			if (!type.HasMember("kind") || !type["kind"].IsString()) continue;
			std::string_view kind = type["kind"].GetString();

			if (kind == "constantBuffer")
			{
				reflectionData.reflectionCS.numUniformBuffers++;
				continue;
			}
			if (kind == "samplerState")
			{
				reflectionData.reflectionCS.numSamplers++;
				continue;
			}
			if (kind == "resource")
			{
				if (!type.HasMember("baseShape") || !type["baseShape"].IsString()) continue;
				std::string_view baseShape = type["baseShape"].GetString();

				bool isReadWrite = false;
				if (type.HasMember("access") && type["access"].IsString())
					isReadWrite = std::string_view(type["access"].GetString()) == "readWrite";

				if (baseShape == "structuredBuffer")
				{
					if (isReadWrite) reflectionData.reflectionCS.numReadwriteStorageBuffers++;
					else             reflectionData.reflectionCS.numReadOnlyStorageBuffers++;
				}
				else if (baseShape == "texture2D" ||
					baseShape == "texture2DMS" ||
					baseShape == "textureCube" ||
					baseShape == "texture2DArray")
				{
					// In compute, all texture bindings are storage textures (no sampler involved)
					if (isReadWrite) reflectionData.reflectionCS.numReadwriteStorageTextures++;
					else             reflectionData.reflectionCS.numReadOnlyStorageTextures++;  
				}
				continue;
			}
		}
	}

	static void mapComputeThreadCount(const rapidjson::Value& entryPoints, ShaderReflectionData& reflectionData)
	{
		for (const auto& ep : entryPoints.GetArray())
		{
			if (!ep.HasMember("threadGroupSize") || !ep["threadGroupSize"].IsArray()) continue;
			const auto& tgs = ep["threadGroupSize"].GetArray();
			if (tgs.Size() >= 3)
			{
				reflectionData.reflectionCS.threadCountX = tgs[0].GetUint();
				reflectionData.reflectionCS.threadCountY = tgs[1].GetUint();
				reflectionData.reflectionCS.threadCountZ = tgs[2].GetUint();
			}
			break; // compute shaders have one entry point
		}
	}

	static SDL_GPUVertexElementFormat slangTypeToVertexFormat(const rapidjson::Value& type)
	{
		if (!type.HasMember("kind") || !type["kind"].IsString())
			return SDL_GPU_VERTEXELEMENTFORMAT_INVALID;

		std::string_view kind = type["kind"].GetString();

		if (kind == "vector")
		{
			if (!type.HasMember("elementCount") || !type.HasMember("elementType"))
				return SDL_GPU_VERTEXELEMENTFORMAT_INVALID;

			int elementCount = type["elementCount"].GetInt();

			const auto& elementType = type["elementType"];
			if (!elementType.HasMember("scalarType") || !elementType["scalarType"].IsString())
				return SDL_GPU_VERTEXELEMENTFORMAT_INVALID;

			std::string_view scalarType = elementType["scalarType"].GetString();

			if (scalarType == "float32")
			{
				switch (elementCount)
				{
				case 2: return SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2;
				case 3: return SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3;
				case 4: return SDL_GPU_VERTEXELEMENTFORMAT_FLOAT4;
				default: return SDL_GPU_VERTEXELEMENTFORMAT_INVALID;
				}
			}
			else if (scalarType == "int32")
			{
				switch (elementCount)
				{
				case 2: return SDL_GPU_VERTEXELEMENTFORMAT_INT2;
				case 3: return SDL_GPU_VERTEXELEMENTFORMAT_INT3;
				case 4: return SDL_GPU_VERTEXELEMENTFORMAT_INT4;
				default: return SDL_GPU_VERTEXELEMENTFORMAT_INVALID;
				}
			}
			else if (scalarType == "uint32")
			{
				switch (elementCount)
				{
				case 2: return SDL_GPU_VERTEXELEMENTFORMAT_UINT2;
				case 3: return SDL_GPU_VERTEXELEMENTFORMAT_UINT3;
				case 4: return SDL_GPU_VERTEXELEMENTFORMAT_UINT4;
				default: return SDL_GPU_VERTEXELEMENTFORMAT_INVALID;
				}
			}
		}
		else if (kind == "scalar")
		{
			if (!type.HasMember("scalarType") || !type["scalarType"].IsString())
				return SDL_GPU_VERTEXELEMENTFORMAT_INVALID;

			std::string_view scalarType = type["scalarType"].GetString();

			if (scalarType == "float32") return SDL_GPU_VERTEXELEMENTFORMAT_FLOAT;
			if (scalarType == "int32")   return SDL_GPU_VERTEXELEMENTFORMAT_INT;
			if (scalarType == "uint32")  return SDL_GPU_VERTEXELEMENTFORMAT_UINT;
		}

		return SDL_GPU_VERTEXELEMENTFORMAT_INVALID;
	}

	static uint32_t vertexElementFormatSize(SDL_GPUVertexElementFormat fmt)
	{
		switch (fmt)
		{
		case SDL_GPU_VERTEXELEMENTFORMAT_FLOAT:  return 4;
		case SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2: return 8;
		case SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3: return 12;
		case SDL_GPU_VERTEXELEMENTFORMAT_FLOAT4: return 16;
		case SDL_GPU_VERTEXELEMENTFORMAT_INT:    return 4;
		case SDL_GPU_VERTEXELEMENTFORMAT_INT2:   return 8;
		case SDL_GPU_VERTEXELEMENTFORMAT_INT3:   return 12;
		case SDL_GPU_VERTEXELEMENTFORMAT_INT4:   return 16;
		case SDL_GPU_VERTEXELEMENTFORMAT_UINT:   return 4;
		case SDL_GPU_VERTEXELEMENTFORMAT_UINT2:  return 8;
		case SDL_GPU_VERTEXELEMENTFORMAT_UINT3:  return 12;
		case SDL_GPU_VERTEXELEMENTFORMAT_UINT4:  return 16;
		default:                                 return 0;
		}
	}

	static void mapVertexAttributes(const rapidjson::Value& entryPoint, ShaderReflectionData& reflectionData)
	{
		if (!entryPoint.HasMember("parameters") || !entryPoint["parameters"].IsArray())
			return;

		for (const auto& param : entryPoint["parameters"].GetArray())
		{
			if (!param.HasMember("binding") || !param["binding"].IsObject()) continue;
			if (!param.HasMember("type") || !param["type"].IsObject())    continue;

			const auto& binding = param["binding"];
			if (!binding.HasMember("kind") || !binding["kind"].IsString())   continue;

			// Only process varyingInput structs (skip SV_INSTANCEID etc.)
			if (std::string_view(binding["kind"].GetString()) != "varyingInput") continue;

			const auto& type = param["type"];
			if (!type.HasMember("kind") || !type["kind"].IsString())         continue;
			if (std::string_view(type["kind"].GetString()) != "struct")      continue;
			if (!type.HasMember("fields") || !type["fields"].IsArray())      continue;

			uint32_t offset = 0;

			for (const auto& field : type["fields"].GetArray())
			{
				if (!field.HasMember("binding") || !field["binding"].IsObject()) continue;
				if (!field.HasMember("type") || !field["type"].IsObject())    continue;

				const auto& fieldBinding = field["binding"];
				if (!fieldBinding.HasMember("kind") || !fieldBinding["kind"].IsString()) continue;

				// Skip system-value semantics like SV_POSITION
				if (field.HasMember("semanticName") && field["semanticName"].IsString())
				{
					std::string_view semantic = field["semanticName"].GetString();
					if (semantic.starts_with("SV_")) continue;
				}

				if (std::string_view(fieldBinding["kind"].GetString()) != "varyingInput") continue;

				uint32_t location = fieldBinding.HasMember("index") && fieldBinding["index"].IsInt()
					? fieldBinding["index"].GetUint()
					: 0;

				SDL_GPUVertexElementFormat fmt = slangTypeToVertexFormat(field["type"]);
				if (fmt == SDL_GPU_VERTEXELEMENTFORMAT_INVALID)
				{
					LogWarn(LOG_RENDER, "Unsupported vertex attribute type for field '%s'",
						field.HasMember("name") ? field["name"].GetString() : "unknown");
					continue;
				}

				SDL_GPUVertexAttribute attrib{};
				attrib.location = location;
				attrib.buffer_slot = 0;       // single interleaved vertex buffer
				attrib.format = fmt;
				attrib.offset = offset;

				reflectionData.vertexAttributes.push_back(attrib);

				uint32_t size = vertexElementFormatSize(fmt);
				offset += size;
				reflectionData.vertexStride += size;
			}
		}
	}

	static SDL_GPUFillMode toFillMode(const std::string& s)
	{
		if (s == "LINE") return SDL_GPU_FILLMODE_LINE;
		return SDL_GPU_FILLMODE_FILL;
	}

	static SDL_GPUCullMode toCullMode(const std::string& s)
	{
		if (s == "NONE")  return SDL_GPU_CULLMODE_NONE;
		if (s == "FRONT") return SDL_GPU_CULLMODE_FRONT;
		return SDL_GPU_CULLMODE_BACK;
	}

	static SDL_GPUFrontFace toFrontFace(const std::string& s)
	{
		if (s == "CLOCKWISE") return SDL_GPU_FRONTFACE_CLOCKWISE;
		return SDL_GPU_FRONTFACE_COUNTER_CLOCKWISE;
	}

	static SDL_GPUPrimitiveType toPrimitiveType(const std::string& s)
	{
		if (s == "POINTLIST")    return SDL_GPU_PRIMITIVETYPE_POINTLIST;
		if (s == "LINELIST")     return SDL_GPU_PRIMITIVETYPE_LINELIST;
		if (s == "LINESTRIP")    return SDL_GPU_PRIMITIVETYPE_LINESTRIP;
		if (s == "TRIANGLESTRIP") return SDL_GPU_PRIMITIVETYPE_TRIANGLESTRIP;
		return SDL_GPU_PRIMITIVETYPE_TRIANGLELIST;
	}

	static SDL_GPUCompareOp toCompareOp(const std::string& s)
	{
		if (s == "NEVER")            return SDL_GPU_COMPAREOP_NEVER;
		if (s == "EQUAL")            return SDL_GPU_COMPAREOP_EQUAL;
		if (s == "LESS_OR_EQUAL")    return SDL_GPU_COMPAREOP_LESS_OR_EQUAL;
		if (s == "GREATER")          return SDL_GPU_COMPAREOP_GREATER;
		if (s == "NOT_EQUAL")        return SDL_GPU_COMPAREOP_NOT_EQUAL;
		if (s == "GREATER_OR_EQUAL") return SDL_GPU_COMPAREOP_GREATER_OR_EQUAL;
		if (s == "ALWAYS")           return SDL_GPU_COMPAREOP_ALWAYS;
		return SDL_GPU_COMPAREOP_LESS;
	}

	static SDL_GPUTextureFormat toTextureFormat(const std::string& s)
	{
		if (s == "R8G8B8A8_UNORM")      return SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM;
		if (s == "R32_UINT")            return SDL_GPU_TEXTUREFORMAT_R32_UINT;
		if (s == "D32_FLOAT")           return SDL_GPU_TEXTUREFORMAT_D32_FLOAT;
		if (s == "D32_FLOAT_S8_UINT")   return SDL_GPU_TEXTUREFORMAT_D32_FLOAT_S8_UINT;
		if (s == "B8G8R8A8_UNORM")      return SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM;
		if (s == "R16G16B16A16_FLOAT")  return SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT;
		LogWarn(LOG_RENDER, "Unknown texture format string: %s, defaulting to R8G8B8A8_UNORM", s.c_str());
		return SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM;
	}

	static SDL_GPUColorTargetBlendState toBlendState(const std::string& s)
	{
		SDL_GPUColorTargetBlendState blend{};
		if (s == "ALPHA")
		{
			blend.enable_blend = true;
			blend.src_color_blendfactor = SDL_GPU_BLENDFACTOR_SRC_ALPHA;
			blend.dst_color_blendfactor = SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
			blend.color_blend_op = SDL_GPU_BLENDOP_ADD;
			blend.src_alpha_blendfactor = SDL_GPU_BLENDFACTOR_ONE;
			blend.dst_alpha_blendfactor = SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
			blend.alpha_blend_op = SDL_GPU_BLENDOP_ADD;
		}
		else if (s == "ADDITIVE")
		{
			blend.enable_blend = true;
			blend.src_color_blendfactor = SDL_GPU_BLENDFACTOR_ONE;
			blend.dst_color_blendfactor = SDL_GPU_BLENDFACTOR_ONE;
			blend.color_blend_op = SDL_GPU_BLENDOP_ADD;
			blend.src_alpha_blendfactor = SDL_GPU_BLENDFACTOR_ONE;
			blend.dst_alpha_blendfactor = SDL_GPU_BLENDFACTOR_ONE;
			blend.alpha_blend_op = SDL_GPU_BLENDOP_ADD;
		}
		// NONE → blend disabled, all fields zeroed/false by default
		return blend;
	}

	static void mapUserAttribs(const rapidjson::Value& param, ShaderReflectionData& reflectionData,
		const std::string metadataFileName)
	{
		if (!param.HasMember("userAttribs") || !param["userAttribs"].IsArray()) {
			return;
		}
			
		for (const auto& attrib : param["userAttribs"].GetArray())
		{
			if (!attrib.HasMember("name") || !attrib["name"].IsString())		   continue;
			if (!attrib.HasMember("arguments") || !attrib["arguments"].IsArray())  continue;
			if (attrib["arguments"].Size() == 0)                                   continue;
			if (!attrib["arguments"][0].IsString())                                continue;

			std::string name = attrib["name"].GetString();
			std::string value = attrib["arguments"][0].GetString();

			if (name == "FillMode")
			{
				reflectionData.fillMode = toFillMode(value);
			}
			else if (name == "CullMode") {

				reflectionData.cullMode = toCullMode(value);
			}
			else if (name == "FrontFace") {
				reflectionData.frontFace = toFrontFace(value);

			}
			else if (name == "PrimitiveType") {
				reflectionData.primitiveType = toPrimitiveType(value);

			}
			else if (name == "DepthCompareOp") {

				reflectionData.depthCompareOp = toCompareOp(value);

			}
			else if (name == "BlendState") {
				reflectionData.blendState = toBlendState(value);

			}
			else if (name == "DepthFormat") {
				reflectionData.depthFormat = toTextureFormat(value);

			}
			else if (name == "ColorTarget") {
				reflectionData.colorTargets.push_back(toTextureFormat(value));

			}
			else if (name == "DepthTest") {
				reflectionData.msaaCapable = (value != "FALSE");

			}
			else if (name == "DepthWrite") {
				reflectionData.msaaCapable = (value != "FALSE");

			}
			else if (name == "MsaaCapable") {
				reflectionData.msaaCapable = (value != "FALSE");
			}
			else if (name == "StencilMode") 
				reflectionData.enableStencilTest = (value != "FALSE");
			else
			{
				LogWarn(LOG_RENDER, "Unknown userAttrib: %s in %s", name.c_str(), metadataFileName.c_str());
			}
		}
	}

};
